### ISSUE TITLE
Report failure on non-200 response code from auth token server

### ISSUE THREAD

**Issue by joe94** [xmidt-org/parodus#334]
### Behaviors

**Current**: parodus uses the response body from the auth token server even when the server responded with a non-200 status code.

**Expected/Recommended**: parodus should only use the response body as as an auth token when the server responded with a 200 (successful) code.

Link to relevant code: https://github.com/xmidt-org/parodus/blob/master/src/auth_token.c#L140

It would look something like
```
if(response_code == 200) {
    ParodusInfo("Received successful response from auth token server\n");
} else {
    ParodusError("Received failed response from auth token server\n"); 
    //perhaps log the code and the response body 

    return -1 // failure
}

...
return 0 // success

```

**Comment by shilpa24balaji** [comment]
@sadhyama Please check, I am guessing its done this way due to curl c library write function callback constraint. Logically this suggestion is valid, so let us see if we can anyway handle it.

**Comment by sadhyama** [comment]
Yes, this change can be added there is no constraint from curl write function callback.
Initially this change was present and token was updated only for response code 200, as part of below PR it was modified for all response codes. This can be modified as suggested.

https://github.com/xmidt-org/parodus/pull/302/commits/51326757003a443eb067d9005342710a5700a880#diff-d2122ac9d92c62c0b0a54578d300d879L153

**Comment by joe94** [comment]
Thanks for checking @sadhyama! I think that change will be helpful for you guys to protect parodus from  auth token server errors.

**Comment by sadhyama** [comment]
Change is merged as part of PR https://github.com/xmidt-org/parodus/pull/335/
