### ISSUE TITLE
parodus client setup for webpa server getting  TLS negation error

### ISSUE THREAD

**Issue by vivekjayachandran** [xmidt-org/parodus#377]
We are getting a TLS negotiation error from parodus when it's trying to connect to a  server & need some support on resolving this.

Dec 10 06:33:58 raspberrypi-rdk-mc "parodus"[11716]: 211210-06:33:58.508328 [mod=PARODUS, lvl=ERROR] [tid=11716] PARODUS: ../../git/src/nopoll_conn.c:817 CERTIFICATE: subject: /CN=10.47.1.250
Dec 10 06:33:58 raspberrypi-rdk-mc "parodus"[11716]: 211210-06:33:58.508381 [mod=PARODUS, lvl=ERROR] [tid=11716] PARODUS: ../../git/src/nopoll_conn.c:819 CERTIFICATE: error 19:self signed certificate in certificate chain
Dec 10 06:33:58 raspberrypi-rdk-mc "parodus"[11716]: 211210-06:33:58.508642 [mod=PARODUS, lvl=ERROR] [tid=11716] PARODUS: ../../git/src/nopoll_conn.c:1105 there was an error with the TLS negotiation, ssl error (code:1) : error:00000001:lib(0):func(0):reason(1)
Dec 10 06:33:58 raspberrypi-rdk-mc "parodus"[11716]: 211210-06:33:58.508719 [mod=PARODUS, lvl=ERROR] [tid=11716] PARODUS: ../../git/src/nopoll_conn.c:535 tls stack: err=337047686, error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed (find reason(code) at openssl/ssl.h)
Dec 10 06:33:58 raspberrypi-rdk-mc "parodus"[11716]: 211210-06:33:58.508770 [mod=PARODUS, lvl=ERROR] [tid=11716] PARODUS: ../../git/src/nopoll_conn.c:556     details, run: openssl errstr 1416F086
Dec 10 06:33:58 raspberrypi-rdk-mc "parodus"[11716]: 211210-06:33:58.509302 [mod=PARODUS, lvl=ERROR] [tid=11716] PARODUS: Error connecting to server
Dec 10 06:33:58 raspberrypi-rdk-mc "parodus"[11716]: 211210-06:33:58.509347 [mod=PARODUS, lvl=ERROR] [tid=11716] PARODUS: RDK-10037 - WebPA Connection Lost

**Comment by schmidtw** [comment]
Parodus ran into a self signed cert & didn't accept it.
